// --- START OF FILE js/state.js ---

export function createInitialState() {
    return {
        isDrawing: false,
        layers: [],
        activeTool: 'brush',
        previousTool: 'brush',
        startPos: null,
        selectedLayers: [],
        currentAction: 'none',
        dragStartPos: null,
        scalingHandle: null,
        activeColor: '#000000',
        activeLineWidth: 3,
        activeLineStyle: 'solid',
        activeTextColor: '#000000',
        activeFontFamily: 'Arial',
        activeFontSize: 30,
        activeFontWeight: 'normal',
        activeFontStyle: 'normal',
        activeTextDecoration: 'none',
        activeTextAlign: 'left',
        lastClickTime: 0,
        clickCount: 0,
        lastClickPos: null,
        originalLayers: [],
        originalBox: null,
        didErase: false,
        tempLayer: null,
        panX: 0,
        panY: 0,
        zoom: 1.0,
        isPanning: false,
        panStartPos: { x: 0, y: 0 },
        rotationStartAngle: 0,
        groupPivot: null,
        groupRotation: 0,
        snapPoint: null,
        lastBrushTime: 0,
        lastBrushPoint: null,
        smoothingAmount: 2,
        shapeRecognitionTimer: null,
        shapeWasJustRecognized: false,
        eraserTrailNodes: [],
        eraserAnimationId: null,
        lastEraserPos: { x: 0, y: 0 },
        isEditingText: false,
        layersToErase: new Set(),
        isMultiTouching: false,
        multiTouchState: {},
        mobileShapeState: 'idle',
        mobileFirstPoint: null,
        mobileDragAnchor: null,
        justCreatedText: false,
        toolBeforeSpenEraser: null,
        isSpenEraserActive: false,
        // --- НАЧАЛО ИЗМЕНЕНИЙ: Режим примагничивания ---
        snappingMode: 'manual', // 'manual' or 'auto'
        // --- КОНЕЦ ИЗМЕНЕНИЙ ---
    };
}
// --- END OF FILE js/state.js ---